url: http://lauraslingerland.com
baseurl: ""

# Site settings
title: Laura Slingerland
# email: laura.sling@gmail.com
description: "A portfolio and blog website"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/lsling
  - title: linkedin
    url: https://www.linkedin.com/in/laura-slingerland/
  - title: facebook
    url: https://www.facebook.com/laura.slingerland
  - title: instagram
    url: https://www.instagram.com/lsling/



# Postal address (add as many lines as necessary)
address:
  - line: 3277 Huntington Pl Dr
  - line: Sarasota, FL 34237

# Build settings
markdown: kramdown
permalink: pretty
